### ISSUE TITLE
pio train produces errors.   - Data set is empty, make sure event fields match imported data.

### ISSUE THREAD

**Issue by washingon** [peoplehum/BagOfWords_SentimentAnalysis_Template#2]
pio train produces errors.
no data found..

engine.json:
{
  "id": "default",
  "description": "Default settings",
  "engineFactory": "com.coviam.sentimentAnalysis.engine.SA_EngineFactory",
  "datasource": {
    "params" : {
      "appName" : "SentimentAnalysis",
      "evalK" : 3
    }
  },
  "preparator": {
    "params": {
      "nGram": 1
    }
  },
  "algorithms": [
    {
      "name": "Naivebayes",
      "params": {
        "lambda" : 1
      }
    }
  ]
}

pio app list
[INFO] [Pio$]                 Name |   ID |                                                       Access Key | Allowed Event(s)
[INFO] [Pio$]    SentimentAnalysis |    9 | myaccesskey | (all)

step 1.. python data/import_eventServer.py --access_key myaccesskey --file data/sample.csv
400 events are imported.

step 2.. pio build     successful
[INFO] [Engine$] Compilation finished successfully.
[INFO] [Engine$] Looking for an engine...
[INFO] [Engine$] Found SantimentAnalysis_BagOfWords_Model-assembly-1.0-deps.jar
[INFO] [Engine$] Found santimentanalysis_bagofwords_model_2.10-1.0.jar
[INFO] [Engine$] Build finished successfully.
[INFO] [Pio$] Your engine is ready for training.

step 3...pio train 
errors..
[INFO] [Engine] Extracting datasource params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.
[INFO] [Engine] Datasource params: (,DataSourceParam(SentimentAnalysis,3))
[INFO] [Engine] Extracting preparator params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.
[INFO] [Engine] Preparator params: (,PreparatorParams(0))
[INFO] [Engine] Extracting serving params...
[INFO] [Engine] Serving params: (,Empty)
[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.5.140:46108]
[INFO] [Engine$] EngineWorkflow.train
[INFO] [Engine$] DataSource: com.coviam.sentimentAnalysis.engine.DataSource@76e9f00b
[INFO] [Engine$] Preparator: com.coviam.sentimentAnalysis.engine.DataPreparator@51dae791
[INFO] [Engine$] AlgorithmList: List(com.coviam.sentimentAnalysis.engine.Algorithm@365cdacf)
[INFO] [Engine$] Data sanity check is on.
[INFO] [Engine$] com.coviam.sentimentAnalysis.engine.TrainingData supports data sanity check. Performing check.
(sample observation,0)

Data set is empty, make sure event fields match imported data.

Exception in thread "main" java.lang.IllegalArgumentException: ngram_954cba544c3d parameter n given invalid value 0.
        at org.apache.spark.ml.param.Param.validate(params.scala:76)
        at org.apache.spark.ml.param.ParamPair.<init>(params.scala:509)
        at org.apache.spark.ml.param.Param.$minus$greater(params.scala:85)
        at org.apache.spark.ml.param.Params$class.set(params.scala:604)
        at org.apache.spark.ml.PipelineStage.set(Pipeline.scala:43)
        at org.apache.spark.ml.feature.NGram.setN(NGram.scala:52)
        at com.coviam.sentimentAnalysis.engine.DataPreparator.processPhrase(DataPreparator.scala:31)
        at com.coviam.sentimentAnalysis.engine.DataPreparator.prepare(DataPreparator.scala:18)
        at com.coviam.sentimentAnalysis.engine.DataPreparator.prepare(DataPreparator.scala:12)
        at org.apache.predictionio.controller.PPreparator.prepareBase(PPreparator.scala:37)
        at org.apache.predictionio.controller.Engine$.train(Engine.scala:671)
        at org.apache.predictionio.controller.Engine.train(Engine.scala:177)
        at org.apache.predictionio.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:67)
        at org.apache.predictionio.workflow.CreateWorkflow$.main(CreateWorkflow.scala:250)
        at org.apache.predictionio.workflow.CreateWorkflow.main(CreateWorkflow.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by washingon** [comment]
verified that events are recorded. for app

```
curl -i -X GET "http://localhost:7070/events.json?accessKey=myaccesskey"
HTTP/1.1 200 OK
Server: spray-can/1.3.3
Date: Sun, 09 Apr 2017 13:06:46 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 5721

[{"eventId":"f90f53cedd7142f391b953513fe88dbf","event":"train","entityType":"wiki_page","entityId":"1","properties":{"phrase":"                   I didn't missed the New Moon trailer...","sentiment":0.0},"eventTime":"2017-04-09T13:02:21.811Z","creationTime":"2017-04-09T13:02:21.815Z"},{"eventId":"1b7780c0ffec4aa4bfae1c4f74e37776","event":"train","entityType":"wiki_page","entityId":"2","properties":{"phrase":"              omg its already 7:30 never come :O","sentiment":1.0},"eventTime":"2017-04-09T13:02:21.833Z","creationTime":"2017-04-09T13:02:21.836Z"},{"eventId":"72b2641b1d0b486bb79ab62f6a2860ad","event":"train","entityType":"wiki_page","entityId":"3","properties":{"phrase":"          .. Omgaga. Im sooo  im gunna CRy. I've been at this dentist since 11.. I was suposed 2 just get a crown put on (30mins)...","sentiment":0.0},"eventTime":"2017-04-09T13:02:21.868Z","creationTime":"2017-04-09T13:02:21.871Z"},{"eventId":"ad43fcde07944530b128b9ae1cf23663","event":"train","en
```

**Comment by bansarishah** [comment]
Hey, I have committed some changes just now. Please clone this template again and train your model. If you found errors again please put here.

**Comment by washingon** [comment]
that fixed the issue.
